### PR TITLE
test circle ci by updating URL

### PR DESCRIPTION
**Pull request by lukebaker**

### CODE REVIEW

**Comment by lukebaker** [comment]
@ckcollab Should I see Circle CI tests on this pull request per #2? I'm not seeing any at the moment.

**Comment by ckcollab** [comment]
Yeah, I was confused for a second as well but I saw this on CircleCI:

image


And then I had to expand this to see it:

image

You can also tell by this green check mark:
image

So it does appear to be working, just a little hard to tell right now :)

**Comment by lukebaker** [comment]
Ah, sure enough. I didn't see that. Thanks!

**Comment by ckcollab** [comment]
No problemo :)

**Pull request merged**
